FROM node:18-alpine3.17 as build



COPY . .

# Delete .env file
RUN rm -rf .env

RUN npm install
RUN npm run build

FROM ubuntu


RUN apt-get update
RUN apt-get install nginx -y
COPY --from=build /dist /var/www/html/

EXPOSE 8080


CMD ["nginx","-g","daemon off;"]