apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-permissions-binding
subjects:
  - kind: User
    name: github-actions@cloud-m2-412515.iam.gserviceaccount.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: all-permissions
  apiGroup: rbac.authorization.k8s.io
