FROM node:18.18-alpine

# Copy package.json and package-lock.json to the container
COPY package*.json ./


RUN npm install -g pnpm

# Install dependencies
RUN pnpm install

# Copy the rest of your application code to the container
COPY . .

ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

RUN npx prisma generate

EXPOSE 3000

# Define the command to run your application
CMD ["pnpm", "run","dev"]

